server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #配置网关gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route1 # 路由ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的地址
          uri: lb://provider-payment  #匹配后提供服务的地址
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由
        - id: payment_route2 # 路由ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的地址
          uri: lb://provider-payment #匹配后提供服务的地址,provider-payment包含多个服务的
          #就会使用负载均衡去依次调用相关服务接口
          predicates: #断言
            - Path=/payment/lb/**  #路径相匹配的进行路由
          #表示在这个时间之间路径才能生效，访问才能成功
          #时间获取方法：ZonedDateTime now = ZonedDateTime.now(); //默认时区
            #- After=2020-12-28T19:29:19.826+08:00[Asia/Shanghai]
            #- Before=2021-12-28T19:29:19.826+08:00[Asia/Shanghai]
          #设置携带cookie才能访问
            #- Cookie=username,david
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
            # 过滤
            #filters:
            #  - AddRequestHeader=X-Request-red, blue



eureka:
  instance:
    hostname: cloud-gateway
  client:
    register-with-eureka: true #表示是否要将自己注册进eureka server默认true
    #是否从eureka抓取已有的注册信息，默认是true,单节点无所谓，集群必须设置成true才能配合ribbon使用负载均衡
    #fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka  单机版
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/