server:
  port: 8006

spring:
  application:
    name: provider-hystrix-payment


eureka:
  client:
    register-with-eureka: true #表示是否要将自己注册进eureka server默认true
    #是否从eureka抓取已有的注册信息，默认是true,单节点无所谓，集群必须设置成true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka  单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #指定进入eureka服务的实例名称，方便在eureka上看到是哪台机器（ip ：port）的服务提供者
  instance:
    instance-id: payment8006    #指定实例名称
    prefer-ip-address: true     #访问地址可以显示IP 鼠标放在eureka服务页面的服务实例名称上，页面左下角即可显示
    #eureka客户端向服务端发送心跳的时间间隔，单位为秒，默认是30秒
    #lease-renewal-interval-in-seconds: 1  #这里改成1秒
    #eureka服务在收到最后一次心跳后等待时间上限，单位为秒，默认是90秒，超时将踢出服务
    #lease-expiration-duration-in-seconds: 2