spring:
  profiles:
    active: dev # 表示开发环境
    #active: test # 表示测试环境
    #active: info
    #根据加载顺序，先从bootstrap.yml上读取配置文件，然后再拼接上这个配置，读取github上 -dev.yml的配置文件
    # nacos可视化页面配置了2个data ID ,切换成开发或者测试，就会从nacos上读取相应的 Data ID 里的配置文件