server:
  port: 1001

spring:
  application:
    name: cloud-config-center #注册进eureka服务器的微服务名称

  cloud:
    config:
      server:
        git:
          uri: git@github.com:zzyybs/springCloud-config.git  #gethub 上面的git仓库名称
          #搜索目录
          search-paths:
            - springCloud-config
      #读取分支
      label: master
#服务注册到eureka地址
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/