server:
  port: 6004

spring:
  application:
    name: consumer-order



eureka:
  client:
    #feign 本身就是一个客户端，这里不用把它注册进eureka了，所以设置为false
    register-with-eureka: false #表示是否要将自己注册进eureka server默认true表示注册进eureka
    #是否从eureka抓取已有的注册信息，默认是true,单节点无所谓，集群必须设置成true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka  单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

      #设置feign客户端超时时间（openFeign 默认支持Ribbon）
ribbon:
    #指的是建立连接所用的时间，适用于网络状况正常下，两端连接所用时间
  ReadTimeout: 5000
    #指的是建立连接后，从服务器读取到可用资源的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign 日志以什么级别监控哪个接口
    com.david.service.PaymentFeignService: debug