server:
  port: 6003

spring:
  application:
    name: consumer-order
#启动consul :  consul agent -dev
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

